version: '3.4'

networks:
  frontend:
  backend:

services:
  webmvc:
    build: 
      context: ..\WebMVC
      dockerfile: Dockerfile
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      CatalogUrl: http://eventcatalog 
      IdentityUrl: http://10.231.64.31:5025
      #CartUrl: htt://cart 
      #OrderUrl: htt://order  
    container_name: webshop
    ports:
      - "5300:80"
    networks:
      - frontend
    depends_on: 
      - eventcatalog  
      - tokenserver

  eventcatalog:
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    image: events/eventsbritecatalogapi    
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalogDB
      DatabaseUser: sa
      DatabaseUserPassword: EventApi(!)
    container_name: eventsbritecatalogapi
    ports:
      - "5049:80"
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  tokenserver:
    build: 
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    environment: 
      ASPNETCORE_ENVIRONMENT: Development 
      MvcClient: http://localhost:5300  
      BasketApiClient: http://localhost:5055
      OrderApiClient: http://localhost:5605
    container_name: tokenserviceeventapi
    ports:
      - "5025:80"
    networks:
      - backend
      - frontend 
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    ports:
      - "1449:1433"

    container_name: mssqlcontainer3
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    networks:
      - backend