version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalog:
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    image: events/eventsbritecatalogapi    
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalogDB
      DatabaseUser: sa
      DatabaseUserPassword: EventApi(!)
    container_name: eventsbritecatalogapi
    ports:
      - "5049:80"
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  tokenserver:
    build: 
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    environment: 
      ASPNETCORE_ENVIRONMENT: Development 
      MvcClient: http://localhost:61514  
      BasketApiClient: http://localhost:5055
      OrderApiClient: http://localhost:5605
    container_name: tokenserviceapi
    ports:
      - "5021:80"
    networks:
      - backend
      - frontend 
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    ports:
      - "1449:1433"

    container_name: mssqlcontainer3
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    networks:
      - backend